# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: []

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Assemble with Gradle
      run: ./gradlew --info assemble
      env:
        repsyUsername: ${{ secrets.repsyUsername }}
        repsyPassword: ${{ secrets.repsyPassword }}
    - name: Test with Gradle
      run: ./gradlew --info test
      env:
        repsyUsername: ${{ secrets.repsyUsername }}
        repsyPassword: ${{ secrets.repsyPassword }}
    - name: Publish Snapshot to Repsy
      run: ./gradlew --info publish
      env:
        repsyUsername: ${{ secrets.repsyUsername }}
        repsyPassword: ${{ secrets.repsyPassword }}
    - name: Publish molang to Repsy
      run: ./gradlew -p molang publish
      env:
        repsyUsername: ${{ secrets.repsyUsername }}
        repsyPassword: ${{ secrets.repsyPassword }}
    - name: Publish mclib to Repsy
      run: ./gradlew -p mclib publish
      env:
        repsyUsername: ${{ secrets.repsyUsername }}
        repsyPassword: ${{ secrets.repsyPassword }}
    - name: Publish particlelib to Repsy
      run: ./gradlew -p particlelib publish
      env:
        repsyUsername: ${{ secrets.repsyUsername }}
        repsyPassword: ${{ secrets.repsyPassword }}
